Style/Documentation:
  Enable: false
Style/FrozenStringLiteralComment:
  Enable: false
AllCops:
  Exclude:
    - db/**/*
    - spec/spec_helper.rb
    - spec/rails_helper.rb
    - Rakefile
    - bin/**/*
    - config/**/*