language: ruby
rvm:
  - 2.3.1
before_script:
  - bundle exec rails db:create
  - bundle exec rails db:migrate
script:
  - bundle exec rspec spec
notifications:
  email:
    recipients:
      - dbs.noronha@gmail.com
    on_success: always
    on_failure: always
deploy:
  provider: heroku
  api_key: 1ab00e3c-2026-4340-8145-bc9690f2eff8
  app: jobgo
  run: "rails db:migrate"
